name       : anki
version    : 2.1.35
release    : 20
source     :
    - https://github.com/ankitects/anki/archive/2.1.35.tar.gz : 188c0756bd2acda0b5d675c2f8462b4bca32aed451e7ffa495e9de5c387aebd0
license    : AGPL-3.0-or-later
component  : office.notes
networking : yes
summary    : Spaced repetition flashcard program.
description: |
    Anki is a spaced repetition flashcard program. "Anki" is the Japanese word for "memorization". The SM2 algorithm, created for SuperMemo in the late 1980s, forms the basis of the spaced repetition methods employed in the program.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
    - flask-cors
    - git
    - nodejs
    - PyAudio
    - pylint
    - python-beautifulsoup4
    - python-black
    - python-decorator
    - python-distro
    - python-jsonschema
    - python-markdown
    - python-mock
    - python-mypy
    - python-protobuf
    - python-pytest
    - python-qtpy
    - python-requests
    - python-send2trash
    - python-waitress
    - python-wheel
    - rsync
    - rustup
rundeps    :
    - flask-cors
    - gtk2-engine-murrine
    - mpv
    - PyAudio
    - python-decorator
    - python-beautifulsoup4
    - python-jsonschema
    - python-markdown
    - python-protobuf
    - python-qtpy
    - python-qtwebengine
    - python-send2trash
    - python-waitress
setup      : |
    #Fix Makefile and build scripts
    sed -i s/release/$version/ $pkgfiles/0002-fix-makefile.patch
    %apply_patches

    #create some binary links to satisfy rust build scripts
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    ln -sv /usr/bin/ranlib $workdir/.bin/x86_64-solus-linux-ranlib
build      : |
    export PATH="$PATH:$workdir/.bin/"
    make build
install    : |
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/dist/*
    install -Dm00755 qt/runanki $installdir/usr/bin/anki
    install -Dm00644 qt/anki.desktop $installdir/usr/share/applications/anki.desktop
