name       : anki
version    : '2.1.10'
release    : 5
source     :
    - https://github.com/dae/anki/archive/2.1.10.tar.gz : b39785c3340a2cf822ed6b021f53add732e7b5c2bbcf088abdddf9bcacfc2f9e
license    : AGPL-3.0-or-later
component  : office.notes
summary    : Spaced repetition flashcard program.
description: |
    Anki is a spaced repetition flashcard program. "Anki" is the Japanese word for "memorization". The SM2 algorithm, created for SuperMemo in the late 1980s, forms the basis of the spaced repetition methods employed in the program.
builddeps  :
    - pkgconfig(pyside)
    - python-qtpy
rundeps    :
    - PyAudio
    - mpv
    - python-decorator
    - python-beautifulsoup4
    - python-markdown
    - python-qtpy
    - python-send2trash
build      : |
    ./tools/build_ui.sh
install    : |
    %make_install
