name       : anki
version    : 2.1.26
release    : 15
source     :
    - https://github.com/ankitects/anki/archive/2.1.26.tar.gz : f5a0c41f3eebe0e77de9d46f2a5cbbe20f7c3a4787f0f02e1d33f298428acbdf
license    : AGPL-3.0-or-later
component  : office.notes
networking : yes
summary    : Spaced repetition flashcard program.
description: |
    Anki is a spaced repetition flashcard program. "Anki" is the Japanese word for "memorization". The SM2 algorithm, created for SuperMemo in the late 1980s, forms the basis of the spaced repetition methods employed in the program.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(pyside)
    - pkgconfig(python-3.7)
    - git
    - nodejs
    - pip
    - PyAudio
    - pylint
    - python-beautifulsoup4
    - python-click
    - python-decorator
    - python-distro
    - python-jsonschema
    - python-markdown
    - python-mock
    - python-mypy
    - python-protobuf
    - python-pytest
    - python-qtpy
    - python-regex
    - python-requests
    - python-send2trash
    - python-toml
    - python-wheel
    - pyparsing
    - rsync
    - rustup
rundeps    :
    - gtk2-engine-murrine
    - mpv
    - PyAudio
    - python-decorator
    - python-beautifulsoup4
    - python-jsonschema
    - python-markdown
    - python-protobuf
    - python-qtpy
    - python-qtwebengine
    - python-send2trash
setup      : |
    #Fix Makefile and build scripts
    %apply_patches

    #create some binary links to satisfy rust build scripts
    mkdir -p $workdir/.bin
    ln -sv /usr/bin/ar $workdir/.bin/x86_64-solus-linux-ar
    ln -sv /usr/bin/ranlib $workdir/.bin/x86_64-solus-linux-ranlib
build      : |
    export PATH="$PATH:$workdir/.bin/"
    make build
install    : |
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/dist/*
    install -Dm00755 qt/runanki $installdir/usr/bin/anki
    install -Dm00644 qt/anki.desktop $installdir/usr/share/applications/anki.desktop
