name       : anki
version    : 2.1.49
release    : 26
source     :
    - git|https://github.com/ankitects/anki.git : 2.1.49
    - https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 : 4cb534c52cdd47a6223d4596d530e7c9c785438ab3b0a49ff347e991c210b2cd
license    : AGPL-3.0-or-later
component  : office.notes
homepage   : https://apps.ankiweb.net/index.html
networking : yes
summary    : Spaced repetition flashcard program.
description: |
    Anki is a spaced repetition flashcard program. "Anki" is the Japanese word for "memorization". The SM2 algorithm, created for SuperMemo in the late 1980s, forms the basis of the spaced repetition methods employed in the program.
builddeps  :
    - pkgconfig(portaudiocpp)
    - pkgconfig(python3)
    - flask-cors
    - PyAudio
    - pylint
    - python-beautifulsoup4
    - python-black
    - python-decorator
    - python-distro
    - python-jsonschema
    - python-markdown
    - python-maturin
    - python-mock
    - python-mypy
    - python-orjson
    - python-protobuf
    - python-pytest
    - python-qtpy
    - python-requests
    - python-send2trash
    - python-stringcase
    - python-waitress
    - python-wheel
rundeps    :
    - flask-cors
    - gtk2-engine-murrine
    - mpv
    - PyAudio
    - python-decorator
    - python-distro
    - python-beautifulsoup4
    - python-jsonschema
    - python-markdown
    - python-orjson
    - python-protobuf
    - python-qtpy
    - python-qtwebengine
    - python-send2trash
    - python-stringcase
    - python-waitress
ccache     : no
setup      : |
    install -Dm00755 $sources/bazelisk-linux-amd64 $workdir/bazel
    # Use system Python
    echo "build --action_env=PYO3_PYTHON=/usr/bin/python3.9" > $workdir/user.bazelrc
build      : |
    ./bazel build --config opt dist
install    : |
    tar xvf $workdir/bazel-bin/dist.tar
    pip3 install --isolated --root=$installdir --ignore-installed --no-deps $workdir/bazel-dist/*
    install -dm00644 $installdir/usr/share/applications
    install -Dm00644 $workdir/qt/linux/anki.desktop $installdir/usr/share/applications/anki.desktop
